//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKSoftware.Tychron.Middleware.TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RKSoftware.Tychron.Middleware.TextResources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the Data is required..
        /// </summary>
        internal static string ReceiveMmsDataRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Data is required..
        /// </summary>
        internal static string ReceiveMmsDlrDataRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the From is required..
        /// </summary>
        internal static string ReceiveMmsDlrFromRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Id is required..
        /// </summary>
        internal static string ReceiveMmsDlrIdRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the InsertedAt is required..
        /// </summary>
        internal static string ReceiveMmsDlrInsertedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrInsertedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Kind is required..
        /// </summary>
        internal static string ReceiveMmsDlrKindRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrKindRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Metadata is required..
        /// </summary>
        internal static string ReceiveMmsDlrMetadataRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrMetadataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the StatusCode is required..
        /// </summary>
        internal static string ReceiveMmsDlrStatusCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrStatusCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Timestamp is required..
        /// </summary>
        internal static string ReceiveMmsDlrTimestampRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrTimestampRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the To is required..
        /// </summary>
        internal static string ReceiveMmsDlrToRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the From is required..
        /// </summary>
        internal static string ReceiveMmsFromRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the Id is required..
        /// </summary>
        internal static string ReceiveMmsIdRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the InsertedAt is required..
        /// </summary>
        internal static string ReceiveMmsInsertedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsInsertedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the Kind is required..
        /// </summary>
        internal static string ReceiveMmsKindRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsKindRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the Metadata is required..
        /// </summary>
        internal static string ReceiveMmsMetadataRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsMetadataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the Timestamp is required..
        /// </summary>
        internal static string ReceiveMmsTimestampRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsTimestampRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS the To is required..
        /// </summary>
        internal static string ReceiveMmsToRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS Body is required..
        /// </summary>
        internal static string ReceiveSmsBodyRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR DeliveryErrorCode is required..
        /// </summary>
        internal static string ReceiveSmsDlrDeliveryErrorCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrDeliveryErrorCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR DeliveryStatus is required..
        /// </summary>
        internal static string ReceiveSmsDlrDeliveryStatusRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrDeliveryStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR ErrorCode is required..
        /// </summary>
        internal static string ReceiveSmsDlrErrorCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrErrorCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR From is required..
        /// </summary>
        internal static string ReceiveSmsDlrFromRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR ID is required..
        /// </summary>
        internal static string ReceiveSmsDlrIdRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR InsertedAt is required..
        /// </summary>
        internal static string ReceiveSmsDlrInsertedAtCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrInsertedAtCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR InsertedAt is required..
        /// </summary>
        internal static string ReceiveSmsDlrInsertedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrInsertedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR Status is required..
        /// </summary>
        internal static string ReceiveSmsDlrStatusRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR To is required..
        /// </summary>
        internal static string ReceiveSmsDlrToRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR Type is required..
        /// </summary>
        internal static string ReceiveSmsDlrTypeRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR UpdatedAt is required..
        /// </summary>
        internal static string ReceiveSmsDlrUpdatedAtCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrUpdatedAtCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR UpdatedAt is required..
        /// </summary>
        internal static string ReceiveSmsDlrUpdatedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsDlrUpdatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS Encoding is required..
        /// </summary>
        internal static string ReceiveSmsEncodingRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsEncodingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS From is required..
        /// </summary>
        internal static string ReceiveSmsFromRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS ID is required..
        /// </summary>
        internal static string ReceiveSmsIdRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS InsertedAt is required..
        /// </summary>
        internal static string ReceiveSmsInsertedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsInsertedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS Priority is required..
        /// </summary>
        internal static string ReceiveSmsPriorityRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsPriorityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS  ProcessedAt is required..
        /// </summary>
        internal static string ReceiveSmsProcessedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsProcessedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS To is required..
        /// </summary>
        internal static string ReceiveSmsToRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS Type is required..
        /// </summary>
        internal static string ReceiveSmsTypeRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS  UpdatedAt is required..
        /// </summary>
        internal static string ReceiveSmsUpdatedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveSmsUpdatedAtRequired", resourceCulture);
            }
        }
    }
}
