namespace RKSoftware.Tychron.APIClient.Error;

/// <summary>
/// Response Codes
/// <see href="https://docs.tychron.info/sms-api/sending-sms-via-http/#response-codes"/>
/// </summary>
public class TychronApiException : Exception
{
    private readonly string? _xcdrid;
    private readonly int _statusCode;

    /// <summary>
    /// Initializes a new instance of the <see cref="TychronApiException"/> class.
    /// </summary>
    /// <param name="xcdrid">An ID used to identify the CDR (Call Detail Record) generated by the request. Please provide this ID for any billing questions when contacting support.</param>
    /// <param name="statusCode">Response HTTP Status Code</param>
    /// <param name="message">Error message.</param>
    public TychronApiException(string? xcdrid, int statusCode, string message)
        : base(message)
    {
        _xcdrid = xcdrid;
        _statusCode = statusCode;
    }

    /// <summary>
    /// An ID used to identify the CDR (Call Detail Record) generated by the request. Please provide this ID for any billing questions when contacting support.
    /// </summary>
    public string? XCdrId => _xcdrid;

    /// <summary>
    /// Response HTTP Status Code
    /// </summary>
    public int StatusCode => _statusCode;
}
