//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RK.Tychron.APIClient.TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RK.Tychron.APIClient.TextResources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Data is required..
        /// </summary>
        internal static string ReceiveMmsDlrDataRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the From is required..
        /// </summary>
        internal static string ReceiveMmsDlrFromRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Id is required..
        /// </summary>
        internal static string ReceiveMmsDlrIdRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the InsertedAt is required..
        /// </summary>
        internal static string ReceiveMmsDlrInsertedAtRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrInsertedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Kind is required..
        /// </summary>
        internal static string ReceiveMmsDlrKindRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrKindRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Metadata is required..
        /// </summary>
        internal static string ReceiveMmsDlrMetadataRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrMetadataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the StatusCode is required..
        /// </summary>
        internal static string ReceiveMmsDlrStatusCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrStatusCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the Timestamp is required..
        /// </summary>
        internal static string ReceiveMmsDlrTimestampRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrTimestampRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS DLR the To is required..
        /// </summary>
        internal static string ReceiveMmsDlrToRequired {
            get {
                return ResourceManager.GetString("ReceiveMmsDlrToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR DeliveryErrorCode is required..
        /// </summary>
        internal static string ReceiveSMSDeliveryErrorCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSDeliveryErrorCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR DeliveryStatus is required..
        /// </summary>
        internal static string ReceiveSMSDeliveryStatusRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSDeliveryStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR ErrorCode is required..
        /// </summary>
        internal static string ReceiveSMSErrorCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSErrorCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR From is required..
        /// </summary>
        internal static string ReceiveSMSFromRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR ID is required..
        /// </summary>
        internal static string ReceiveSMSIdRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR InsertedAt is required..
        /// </summary>
        internal static string ReceiveSMSInsertedAtCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSInsertedAtCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR Status is required..
        /// </summary>
        internal static string ReceiveSMSStatusRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR To is required..
        /// </summary>
        internal static string ReceiveSMSToRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR Type is required..
        /// </summary>
        internal static string ReceiveSMSTypeRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS DLR UpdatedAt is required..
        /// </summary>
        internal static string ReceiveSMSUpdatedAtCodeRequired {
            get {
                return ResourceManager.GetString("ReceiveSMSUpdatedAtCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS Message From is required..
        /// </summary>
        internal static string SendMMSFromRequired {
            get {
                return ResourceManager.GetString("SendMMSFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one part of the MMS message is required..
        /// </summary>
        internal static string SendMMSPartRequired {
            get {
                return ResourceManager.GetString("SendMMSPartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one MMS message recipient is required..
        /// </summary>
        internal static string SendMMSToRequired {
            get {
                return ResourceManager.GetString("SendMMSToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Message Body is required..
        /// </summary>
        internal static string SendSMSBodyRequired {
            get {
                return ResourceManager.GetString("SendSMSBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS DLR Message From is required..
        /// </summary>
        internal static string SendSMSFromDlrRequired {
            get {
                return ResourceManager.GetString("SendSMSFromDlrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Message From is required..
        /// </summary>
        internal static string SendSMSFromRequired {
            get {
                return ResourceManager.GetString("SendSMSFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS DLR SmsId is required..
        /// </summary>
        internal static string SendSMSSmsIdRequired {
            get {
                return ResourceManager.GetString("SendSMSSmsIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one SMS message recipient is required..
        /// </summary>
        internal static string SendSMSToRequired {
            get {
                return ResourceManager.GetString("SendSMSToRequired", resourceCulture);
            }
        }
    }
}
