name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build UnitTests/RK.Tychron.Client.Tests/RK.Tychron.Client.Tests.csproj --configuration Release

    - name: Run tests
      run: dotnet test UnitTests/RK.Tychron.Client.Tests/RK.Tychron.Client.Tests.csproj --configuration Release --no-build --collect "XPlat Code Coverage"
    - name: Check test results
      run: |
        test_exit_code=$(dotnet test --list-tests --no-build | grep -q "Total: 0 Passed:"; echo $?)
        if [ "$test_exit_code" -eq 0 ]; then
          echo "Tests failed. Failing the workflow."
          exit 1
        fi

    - name: Upload code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-results
        path: |
          ./UnitTests/RK.Tychron.Client.Tests/TestResults/**/*.xml
